// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $boun_senlikci_index from "./routes/boun-senlikci/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $CourseSelector from "./islands/CourseSelector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/boun-senlikci/index.tsx": $boun_senlikci_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CourseSelector.tsx": $CourseSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
